/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_JK_FF
#(
    parameter Default = 1'b0
)
(
   input J,
   input C,
   input K,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        if (~J & K)
            state <= 1'b0;
         else if (J & ~K)
            state <= 1'b1;
         else if (J & K)
            state <= ~state;
    end

    initial begin
        state = Default;
    end
endmodule


module controller (
  input clk,
  input rst,
  input beginn,
  input reset,
  input zero,
  input endd,
  output start,
  output load,
  output countdown
);
  wire s0;
  assign s0 = (~ rst | reset | zero);
  DIG_JK_FF #(
    .Default(0)
  )
  DIG_JK_FF_i0 (
    .J( beginn ),
    .C( clk ),
    .K( s0 ),
    .Q( start )
  );
  assign load = reset;
  assign countdown = endd;
endmodule
