/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module DIG_Counter_Nbit
#(
    parameter Bits = 2
)
(
    output [(Bits-1):0] out,
    output ovf,
    input C,
    input en,
    input clr
);
    reg [(Bits-1):0] count;

    always @ (posedge C) begin
        if (clr)
          count <= 'h0;
        else if (en)
          count <= count + 1'b1;
    end

    assign out = count;
    assign ovf = en? &count : 1'b0;

    initial begin
        count = 'h0;
    end
endmodule


module counter (
  input clk,
  input start,
  input rst,
  output endd
);
  wire s0;
  wire [9:0] s1;
  wire [9:0] s2;
  wire endd_temp;
  DIG_Counter_Nbit #(
    .Bits(10)
  )
  DIG_Counter_Nbit_i0 (
    .en( start ),
    .C( clk ),
    .clr( s0 ),
    .out( s1 )
  );
  assign s0 = (~ rst | endd_temp);
  assign s2 = ~ s1;
  assign endd_temp = ((s2[0] & s2[1] & s2[2] & ~ s2[3] & s2[4]) & (~ s2[5] & ~ s2[6] & ~ s2[7] & ~ s2[8] & ~ s2[9]));
  assign endd = endd_temp;
endmodule
